/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface SlaRule {
    category: string;
    deadlineNanos: bigint;
}
export interface AuditLog {
    id: bigint;
    action: string;
    requestId: bigint;
    actorId: Principal;
    notes?: string;
    timestamp: Time;
}
export interface User {
    id: Principal;
    name: string;
    role: UserRole;
    department: string;
    managerDelegate?: Principal;
}
export interface ApprovalStep {
    status: string;
    approvedAt?: Time;
    approverRole: string;
    comments?: string;
}
export interface Request {
    id: bigint;
    status: RequestStatus;
    justification: string;
    slaDeadline?: Time;
    cost: number;
    createdAt: Time;
    estimatedCompletion?: Time;
    currentApprover?: Principal;
    employeeId: Principal;
    category: string;
    priority: Priority;
    approvalChain: Array<ApprovalStep>;
    riskLevel: RiskLevel;
    requestType: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface NotificationPreference {
    userId: Principal;
    inAppEnabled: boolean;
}
export interface Notification {
    id: bigint;
    userId: Principal;
    createdAt: Time;
    read: boolean;
    message: string;
}
export interface ApprovalPolicy {
    requiredRoles: Array<string>;
    riskLevel: string;
    requestType: string;
}
export interface UserProfile {
    name: string;
    department: string;
    managerDelegate?: Principal;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum RequestStatus {
    pending = "pending",
    completed = "completed",
    approved = "approved",
    rejected = "rejected",
    moreInfoRequested = "moreInfoRequested",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Add an approval chain policy. Admin-only.
     */
    addApprovalPolicy(requestType: string, riskLevel: string, requiredRoles: Array<string>): Promise<bigint>;
    /**
     * / Manually add an audit log entry. Admin-only.
     */
    addAuditLog(requestId: bigint, action: string, notes: string | null): Promise<void>;
    /**
     * / Add or update a user record. Admin-only.
     */
    addUser(userId: Principal, name: string, role: UserRole, department: string, managerDelegate: Principal | null): Promise<void>;
    /**
     * / Approve a request. Requires #user role (managers / IT admins / finance admins are users with elevated roles).
     */
    approveRequest(requestId: bigint, comments: string | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Assign a role to a user. Admin-only (delegates to access-control which also guards).
     */
    assignUserRole(userId: Principal, role: UserRole): Promise<void>;
    /**
     * / Create a new request. Requires at least #user role.
     */
    createRequest(requestType: string, category: string, justification: string, riskLevel: RiskLevel, priority: Priority, cost: number): Promise<bigint>;
    /**
     * / Get audit logs for a specific request. Requires #user role; non-admins can only view logs for their own requests.
     */
    getAuditLogsForRequest(requestId: bigint): Promise<Array<AuditLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get notification preferences for a user. Users can get their own; admins can get any.
     */
    getNotificationPreference(userId: Principal): Promise<NotificationPreference | null>;
    /**
     * / Get notifications for a user. Users can only fetch their own; admins can fetch any.
     */
    getNotifications(userId: Principal): Promise<Array<Notification>>;
    /**
     * / Get a single request by id. Requires #user role; non-admins can only view their own.
     */
    getRequest(requestId: bigint): Promise<Request>;
    /**
     * / Get requests belonging to a specific user.
     * / Users can only fetch their own requests; admins can fetch any user's requests.
     */
    getRequestsByUser(userId: Principal): Promise<Array<Request>>;
    /**
     * / Get unread notification count. Users can only query their own count; admins can query any.
     */
    getUnreadNotificationCount(userId: Principal): Promise<bigint>;
    /**
     * / Get a specific user. Admins can fetch any user; regular users can only fetch themselves.
     */
    getUser(userId: Principal): Promise<User>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    /**
     * / List all requests. Requires at least #user role (managers/admins use this for the approvals screen).
     */
    listAllRequests(): Promise<Array<Request>>;
    /**
     * / List all approval chain policies. Admin-only.
     */
    listApprovalPolicies(): Promise<Array<ApprovalPolicy>>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    /**
     * / List all audit logs. Admin-only (used in Reports & Export page).
     */
    listAuditLogs(): Promise<Array<AuditLog>>;
    /**
     * / List all SLA rules. Admin-only.
     */
    listSlaRules(): Promise<Array<SlaRule>>;
    /**
     * / List all users. Admin-only (used in Admin Configuration page).
     */
    listUsers(): Promise<Array<User>>;
    /**
     * / Mark a notification as read. Users can only mark their own notifications.
     */
    markNotificationAsRead(userId: Principal, notificationId: bigint): Promise<void>;
    /**
     * / Reject a request. Requires #user role.
     */
    rejectRequest(requestId: bigint, comments: string | null): Promise<void>;
    requestApproval(): Promise<void>;
    /**
     * / Request more information for a request. Requires #user role.
     */
    requestMoreInfo(requestId: bigint, comments: string | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    /**
     * / Set manager delegate for a user. Admin-only.
     */
    setManagerDelegate(userId: Principal, delegate: Principal | null): Promise<void>;
    /**
     * / Set notification preferences for a user. Users can set their own; admins can set any.
     */
    setNotificationPreference(userId: Principal, inAppEnabled: boolean): Promise<void>;
    /**
     * / Set an SLA rule for a request category. Admin-only.
     */
    setSlaRule(category: string, deadlineNanos: bigint): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, ApprovalStep as _ApprovalStep, AuditLog as _AuditLog, NotificationPreference as _NotificationPreference, Priority as _Priority, Request as _Request, RequestStatus as _RequestStatus, RiskLevel as _RiskLevel, Time as _Time, User as _User, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addApprovalPolicy(arg0: string, arg1: string, arg2: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addApprovalPolicy(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addApprovalPolicy(arg0, arg1, arg2);
            return result;
        }
    }
    async addAuditLog(arg0: bigint, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAuditLog(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAuditLog(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addUser(arg0: Principal, arg1: string, arg2: UserRole, arg3: string, arg4: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async approveRequest(arg0: bigint, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRequest(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRequest(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createRequest(arg0: string, arg1: string, arg2: string, arg3: RiskLevel, arg4: Priority, arg5: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRequest(arg0, arg1, arg2, to_candid_RiskLevel_n5(this._uploadFile, this._downloadFile, arg3), to_candid_Priority_n7(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRequest(arg0, arg1, arg2, to_candid_RiskLevel_n5(this._uploadFile, this._downloadFile, arg3), to_candid_Priority_n7(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async getAuditLogsForRequest(arg0: bigint): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogsForRequest(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogsForRequest(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationPreference(arg0: Principal): Promise<NotificationPreference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationPreference(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationPreference(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: Principal): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return result;
        }
    }
    async getRequest(arg0: bigint): Promise<Request> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequest(arg0);
                return from_candid_Request_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequest(arg0);
            return from_candid_Request_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestsByUser(arg0: Principal): Promise<Array<Request>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestsByUser(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestsByUser(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount(arg0);
            return result;
        }
    }
    async getUser(arg0: Principal): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_User_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_User_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listAllRequests(): Promise<Array<Request>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllRequests();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllRequests();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovalPolicies(): Promise<Array<ApprovalPolicy>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovalPolicies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovalPolicies();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAuditLogs(): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAuditLogs();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAuditLogs();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSlaRules(): Promise<Array<SlaRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSlaRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSlaRules();
            return result;
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationAsRead(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0, arg1);
            return result;
        }
    }
    async rejectRequest(arg0: bigint, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRequest(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRequest(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async requestMoreInfo(arg0: bigint, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestMoreInfo(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestMoreInfo(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setManagerDelegate(arg0: Principal, arg1: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setManagerDelegate(arg0, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setManagerDelegate(arg0, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setNotificationPreference(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNotificationPreference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNotificationPreference(arg0, arg1);
            return result;
        }
    }
    async setSlaRule(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSlaRule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSlaRule(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStep_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStep): ApprovalStep {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_AuditLog_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLog): AuditLog {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Request_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Request): Request {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_User_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NotificationPreference]): NotificationPreference | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    action: string;
    requestId: bigint;
    actorId: Principal;
    notes: [] | [string];
    timestamp: _Time;
}): {
    id: bigint;
    action: string;
    requestId: bigint;
    actorId: Principal;
    notes?: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        action: value.action,
        requestId: value.requestId,
        actorId: value.actorId,
        notes: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    department: string;
    managerDelegate: [] | [Principal];
}): {
    name: string;
    department: string;
    managerDelegate?: Principal;
} {
    return {
        name: value.name,
        department: value.department,
        managerDelegate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.managerDelegate))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RequestStatus;
    justification: string;
    slaDeadline: [] | [_Time];
    cost: number;
    createdAt: _Time;
    estimatedCompletion: [] | [_Time];
    currentApprover: [] | [Principal];
    employeeId: Principal;
    category: string;
    priority: _Priority;
    approvalChain: Array<_ApprovalStep>;
    riskLevel: _RiskLevel;
    requestType: string;
}): {
    id: bigint;
    status: RequestStatus;
    justification: string;
    slaDeadline?: Time;
    cost: number;
    createdAt: Time;
    estimatedCompletion?: Time;
    currentApprover?: Principal;
    employeeId: Principal;
    category: string;
    priority: Priority;
    approvalChain: Array<ApprovalStep>;
    riskLevel: RiskLevel;
    requestType: string;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n21(_uploadFile, _downloadFile, value.status),
        justification: value.justification,
        slaDeadline: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.slaDeadline)),
        cost: value.cost,
        createdAt: value.createdAt,
        estimatedCompletion: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.estimatedCompletion)),
        currentApprover: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.currentApprover)),
        employeeId: value.employeeId,
        category: value.category,
        priority: from_candid_Priority_n24(_uploadFile, _downloadFile, value.priority),
        approvalChain: from_candid_vec_n26(_uploadFile, _downloadFile, value.approvalChain),
        riskLevel: from_candid_RiskLevel_n29(_uploadFile, _downloadFile, value.riskLevel),
        requestType: value.requestType
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    approvedAt: [] | [_Time];
    approverRole: string;
    comments: [] | [string];
}): {
    status: string;
    approvedAt?: Time;
    approverRole: string;
    comments?: string;
} {
    return {
        status: value.status,
        approvedAt: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.approvedAt)),
        approverRole: value.approverRole,
        comments: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.comments))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: _UserRole;
    department: string;
    managerDelegate: [] | [Principal];
}): {
    id: Principal;
    name: string;
    role: UserRole;
    department: string;
    managerDelegate?: Principal;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n16(_uploadFile, _downloadFile, value.role),
        department: value.department,
        managerDelegate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.managerDelegate))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n36(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    moreInfoRequested: null;
} | {
    inProgress: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "completed" in value ? RequestStatus.completed : "approved" in value ? RequestStatus.approved : "rejected" in value ? RequestStatus.rejected : "moreInfoRequested" in value ? RequestStatus.moreInfoRequested : "inProgress" in value ? RequestStatus.inProgress : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovalStep>): Array<ApprovalStep> {
    return value.map((x)=>from_candid_ApprovalStep_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Request>): Array<Request> {
    return value.map((x)=>from_candid_Request_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLog>): Array<AuditLog> {
    return value.map((x)=>from_candid_AuditLog_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    department: string;
    managerDelegate?: Principal;
}): {
    name: string;
    department: string;
    managerDelegate: [] | [Principal];
} {
    return {
        name: value.name,
        department: value.department,
        managerDelegate: value.managerDelegate ? candid_some(value.managerDelegate) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
