/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'requestId' : IDL.Nat,
  'actorId' : IDL.Principal,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'department' : IDL.Text,
  'managerDelegate' : IDL.Opt(IDL.Principal),
});
export const NotificationPreference = IDL.Record({
  'userId' : IDL.Principal,
  'inAppEnabled' : IDL.Bool,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'moreInfoRequested' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ApprovalStep = IDL.Record({
  'status' : IDL.Text,
  'approvedAt' : IDL.Opt(Time),
  'approverRole' : IDL.Text,
  'comments' : IDL.Opt(IDL.Text),
});
export const Request = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'justification' : IDL.Text,
  'slaDeadline' : IDL.Opt(Time),
  'cost' : IDL.Float64,
  'createdAt' : Time,
  'estimatedCompletion' : IDL.Opt(Time),
  'currentApprover' : IDL.Opt(IDL.Principal),
  'employeeId' : IDL.Principal,
  'category' : IDL.Text,
  'priority' : Priority,
  'approvalChain' : IDL.Vec(ApprovalStep),
  'riskLevel' : RiskLevel,
  'requestType' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'department' : IDL.Text,
  'managerDelegate' : IDL.Opt(IDL.Principal),
});
export const ApprovalPolicy = IDL.Record({
  'requiredRoles' : IDL.Vec(IDL.Text),
  'riskLevel' : IDL.Text,
  'requestType' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const SlaRule = IDL.Record({
  'category' : IDL.Text,
  'deadlineNanos' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addApprovalPolicy' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addAuditLog' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addUser' : IDL.Func(
      [IDL.Principal, IDL.Text, UserRole, IDL.Text, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'approveRequest' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, RiskLevel, Priority, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'getAuditLogsForRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AuditLog)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotificationPreference' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(NotificationPreference)],
      ['query'],
    ),
  'getNotifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getRequest' : IDL.Func([IDL.Nat], [Request], ['query']),
  'getRequestsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Request)],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func(
      [IDL.Principal],
      [IDL.Nat],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'listApprovalPolicies' : IDL.Func([], [IDL.Vec(ApprovalPolicy)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'listSlaRules' : IDL.Func([], [IDL.Vec(SlaRule)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'rejectRequest' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'requestMoreInfo' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setManagerDelegate' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'setNotificationPreference' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'setSlaRule' : IDL.Func([IDL.Text, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'requestId' : IDL.Nat,
    'actorId' : IDL.Principal,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'department' : IDL.Text,
    'managerDelegate' : IDL.Opt(IDL.Principal),
  });
  const NotificationPreference = IDL.Record({
    'userId' : IDL.Principal,
    'inAppEnabled' : IDL.Bool,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'moreInfoRequested' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ApprovalStep = IDL.Record({
    'status' : IDL.Text,
    'approvedAt' : IDL.Opt(Time),
    'approverRole' : IDL.Text,
    'comments' : IDL.Opt(IDL.Text),
  });
  const Request = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'justification' : IDL.Text,
    'slaDeadline' : IDL.Opt(Time),
    'cost' : IDL.Float64,
    'createdAt' : Time,
    'estimatedCompletion' : IDL.Opt(Time),
    'currentApprover' : IDL.Opt(IDL.Principal),
    'employeeId' : IDL.Principal,
    'category' : IDL.Text,
    'priority' : Priority,
    'approvalChain' : IDL.Vec(ApprovalStep),
    'riskLevel' : RiskLevel,
    'requestType' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'department' : IDL.Text,
    'managerDelegate' : IDL.Opt(IDL.Principal),
  });
  const ApprovalPolicy = IDL.Record({
    'requiredRoles' : IDL.Vec(IDL.Text),
    'riskLevel' : IDL.Text,
    'requestType' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const SlaRule = IDL.Record({
    'category' : IDL.Text,
    'deadlineNanos' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addApprovalPolicy' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addAuditLog' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addUser' : IDL.Func(
        [IDL.Principal, IDL.Text, UserRole, IDL.Text, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'approveRequest' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, RiskLevel, Priority, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'getAuditLogsForRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotificationPreference' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(NotificationPreference)],
        ['query'],
      ),
    'getNotifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getRequest' : IDL.Func([IDL.Nat], [Request], ['query']),
    'getRequestsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Request)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'listApprovalPolicies' : IDL.Func([], [IDL.Vec(ApprovalPolicy)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'listSlaRules' : IDL.Func([], [IDL.Vec(SlaRule)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'rejectRequest' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'requestMoreInfo' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setManagerDelegate' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'setNotificationPreference' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'setSlaRule' : IDL.Func([IDL.Text, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };