/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApprovalPolicy {
  'requiredRoles' : Array<string>,
  'riskLevel' : string,
  'requestType' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ApprovalStep {
  'status' : string,
  'approvedAt' : [] | [Time],
  'approverRole' : string,
  'comments' : [] | [string],
}
export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'requestId' : bigint,
  'actorId' : Principal,
  'notes' : [] | [string],
  'timestamp' : Time,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : Time,
  'read' : boolean,
  'message' : string,
}
export interface NotificationPreference {
  'userId' : Principal,
  'inAppEnabled' : boolean,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Request {
  'id' : bigint,
  'status' : RequestStatus,
  'justification' : string,
  'slaDeadline' : [] | [Time],
  'cost' : number,
  'createdAt' : Time,
  'estimatedCompletion' : [] | [Time],
  'currentApprover' : [] | [Principal],
  'employeeId' : Principal,
  'category' : string,
  'priority' : Priority,
  'approvalChain' : Array<ApprovalStep>,
  'riskLevel' : RiskLevel,
  'requestType' : string,
}
export type RequestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'moreInfoRequested' : null } |
  { 'inProgress' : null };
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface SlaRule { 'category' : string, 'deadlineNanos' : bigint }
export type Time = bigint;
export interface User {
  'id' : Principal,
  'name' : string,
  'role' : UserRole,
  'department' : string,
  'managerDelegate' : [] | [Principal],
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'department' : string,
  'managerDelegate' : [] | [Principal],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add an approval chain policy. Admin-only.
   */
  'addApprovalPolicy' : ActorMethod<[string, string, Array<string>], bigint>,
  /**
   * / Manually add an audit log entry. Admin-only.
   */
  'addAuditLog' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  /**
   * / Add or update a user record. Admin-only.
   */
  'addUser' : ActorMethod<
    [Principal, string, UserRole, string, [] | [Principal]],
    undefined
  >,
  /**
   * / Approve a request. Requires #user role (managers / IT admins / finance admins are users with elevated roles).
   */
  'approveRequest' : ActorMethod<[bigint, [] | [string]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Assign a role to a user. Admin-only (delegates to access-control which also guards).
   */
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new request. Requires at least #user role.
   */
  'createRequest' : ActorMethod<
    [string, string, string, RiskLevel, Priority, number],
    bigint
  >,
  /**
   * / Get audit logs for a specific request. Requires #user role; non-admins can only view logs for their own requests.
   */
  'getAuditLogsForRequest' : ActorMethod<[bigint], Array<AuditLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get notification preferences for a user. Users can get their own; admins can get any.
   */
  'getNotificationPreference' : ActorMethod<
    [Principal],
    [] | [NotificationPreference]
  >,
  /**
   * / Get notifications for a user. Users can only fetch their own; admins can fetch any.
   */
  'getNotifications' : ActorMethod<[Principal], Array<Notification>>,
  /**
   * / Get a single request by id. Requires #user role; non-admins can only view their own.
   */
  'getRequest' : ActorMethod<[bigint], Request>,
  /**
   * / Get requests belonging to a specific user.
   * / Users can only fetch their own requests; admins can fetch any user's requests.
   */
  'getRequestsByUser' : ActorMethod<[Principal], Array<Request>>,
  /**
   * / Get unread notification count. Users can only query their own count; admins can query any.
   */
  'getUnreadNotificationCount' : ActorMethod<[Principal], bigint>,
  /**
   * / Get a specific user. Admins can fetch any user; regular users can only fetch themselves.
   */
  'getUser' : ActorMethod<[Principal], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  /**
   * / List all requests. Requires at least #user role (managers/admins use this for the approvals screen).
   */
  'listAllRequests' : ActorMethod<[], Array<Request>>,
  /**
   * / List all approval chain policies. Admin-only.
   */
  'listApprovalPolicies' : ActorMethod<[], Array<ApprovalPolicy>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  /**
   * / List all audit logs. Admin-only (used in Reports & Export page).
   */
  'listAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  /**
   * / List all SLA rules. Admin-only.
   */
  'listSlaRules' : ActorMethod<[], Array<SlaRule>>,
  /**
   * / List all users. Admin-only (used in Admin Configuration page).
   */
  'listUsers' : ActorMethod<[], Array<User>>,
  /**
   * / Mark a notification as read. Users can only mark their own notifications.
   */
  'markNotificationAsRead' : ActorMethod<[Principal, bigint], undefined>,
  /**
   * / Reject a request. Requires #user role.
   */
  'rejectRequest' : ActorMethod<[bigint, [] | [string]], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  /**
   * / Request more information for a request. Requires #user role.
   */
  'requestMoreInfo' : ActorMethod<[bigint, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  /**
   * / Set manager delegate for a user. Admin-only.
   */
  'setManagerDelegate' : ActorMethod<[Principal, [] | [Principal]], undefined>,
  /**
   * / Set notification preferences for a user. Users can set their own; admins can set any.
   */
  'setNotificationPreference' : ActorMethod<[Principal, boolean], undefined>,
  /**
   * / Set an SLA rule for a request category. Admin-only.
   */
  'setSlaRule' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];